include tokyonight.conf

font_size 14.0
font_family JetBrainsMono NF

cursor none
cursor_blink_interval 0

enable_audio_bell no

remember_window_size  yes
initial_window_width  1000
initial_window_height 480

hide_window_decorations yes
