print_info() {
    info title
    info underline

    info "OS" distro
    info "Kernel" kernel
    info "Packages" packages
    info "Shell" shell
    info "DE" de
    info "WM" wm
    info "Terminal" term

    info cols
}

ascii_distro="linux"
