print_info() {
    info title
    info "OS" distro
    info "Kernel" kernel
    info "Packages" packages
    info "Shell" shell
    info "DE" de
    info "WM" wm
    info "Terminal" term
}

ascii_distro="arch_small"
