backend = "xrender";
vsync = false;
corner-radius = 0;

animations = true;
animation-open-exclude = [
    "class_g = 'Rofi'"
];
animation-unmap-exclude = [
    "class_g = 'Rofi'"
];

shadow = true;
shadow-exclude = [
    "class_g = 'Rofi'",
];

fading = true;
fade-in-step = 0.09;
fade-out-step = 0.09;
