add_newline = true

palette = "onedark"

[palettes.onedark]
red = "#e55561"
green = "#8ebd6b"
blue = "#4fa6ed"
yellow = "#e2b86b"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[✗](bold red)"

[directory]
truncation_length = 100
truncation_symbol = ""
truncate_to_repo = false
use_os_path_sep = false

[git_branch]
symbol = ""
format = "[$symbol $branch](bold #30e248) "

[cmd_duration]
min_time = 500
format = '\([$duration](bold yellow)\) '
