import = ["~/.config/alacritty/onedark.toml"]

[font]
size = 11.0

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[window.padding]
x = 4
y = 4

[window.dimensions]
columns = 80
lines = 25
